language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=Django==1.5.1
install:
  - pip install -q --use-mirrors $DJANGO_VERSION
  - pip install -q --use-mirrors -r requirements.txt
  - pip install -q -e . --use-mirrors
script:
  - python quicktest.py btlib
