language: python
python:
  - "2.7"
install:
  - pip install coveralls --use-mirrors
  - pip install -q --use-mirrors -r requirements.txt
  - pip install -q -e . --use-mirrors
script:
  - coverage run --source=btlib quicktest.py btlib
  - coverage report -m
  - python quicktest.py btlib
after_script:
  - coveralls --verbose
