from django.contrib import admin
from btlib.models import *

admin.site.register(Author)
admin.site.register(Illustrator)
admin.site.register(Genre)
admin.site.register(Publisher)
admin.site.register(ProjectStatus)
admin.site.register(ProjectType)
admin.site.register(Language)
admin.site.register(Novel)
admin.site.register(Volume)
admin.site.register(Chapter)
admin.site.register(Project)
admin.site.register(ProjectTranslation)
admin.site.register(NovelTranslation)
admin.site.register(VolumeTranslation)
admin.site.register(ChapterTranslation)
admin.site.register(Revision)
admin.site.register(Note)
admin.site.register(Image)
