from django.contrib import admin
from btlib.models import *

admin.site.register(Author)
admin.site.register(Illustrator)
admin.site.register(Genre)
admin.site.register(Publisher)
admin.site.register(ProjectStatus)
admin.site.register(ProjectType)
admin.site.register(Language)
admin.site.register(Novel)
admin.site.register(Volume)
admin.site.register(Chapter)
admin.site.register(Project)
admin.site.register(ProjectTrans)
admin.site.register(NovelTrans)
admin.site.register(VolumeTrans)
admin.site.register(ChapterTrans)
admin.site.register(Revision)
admin.site.register(Note)
admin.site.register(Image)
